### ISSUE TITLE
Description of allowed components within functions is incomplete

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2359] opened 2019-05-15 08:21 UTC
The fifth bullet point in section 12.2 of the spec states:

> A function may only contain components of the restricted classes type, record, operator record, and function; i.e. no model or block components.

Stated another way, this says:

> types, records, operator records, and functions are allowed.
> models and blocks are not allowed.

This leaves the allowability of connectors, expandable connectors, operators, and packages undefined.

We either need to enumerate all the disallowed kinds of classes, or change the "i.e." to "e.g." in that bullet point.

**Comment by beutlich** [comment] 2019-05-15 08:24
See also #2308.

**Comment by HansOlsson** [comment] 2019-05-15 10:06
Closed as duplicate of #2308

**Closed by HansOlsson** 2019-05-15 10:06 UTC
Labels: bug
