### ISSUE TITLE
Do we really need MCP for ternary in order to create block with constant output?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2413] opened 2019-09-20 05:31 UTC
This relates to #2211 in view of https://github.com/modelica/ModelicaStandardLibrary/pull/3112.

I want to create a block with `constant` output:
```
 block BooleanConstantVariability
    constant Boolean k = true "Constant output value" annotation(Dialog(group="Constants"));
    extends Interfaces.partialBooleanSource;
  equation
    y = k;
  end BooleanConstantVariability;
```

The problem, as reported in https://github.com/modelica/ModelicaStandardLibrary/pull/3112, is that Dymola doesn't allow the user to change the value of `k`, even though it has a `Dialog` annotation.

Do we really see #2211 as the only solution for this situation,
```
    constant Boolean k = true "Constant output value" annotation(Dialog(visible=True));
```
or could we find consensus around how to use what we already have in order to avoid `k` being hidden?

**Comment by HansOlsson** [comment] 2019-09-20 08:36
> This relates to #2211 in view of modelica/ModelicaStandardLibrary#3112.
...
>The problem, as reported in modelica/ModelicaStandardLibrary#3112, is that Dymola doesn't allow the user to change the value of k, even though it has a Dialog annotation.

Please note that it isn't the only issue raised for that PR. Having constant variables with Dialog-annotation in the parameter-dialog would be straightforward in itself.

However, to me Dialog-annotation just to add a variable to the parameter-dialog should be an exception - and not this normal.


The underlying problem is that this is part of proposal to change the view of constant and parameter-evaluation in general, and to me that would create a large number of changes both in MSL and in user-libraries, and either create more confusion as some parameters would still be evaluated - or lock down current implementation limitations limiting re-use.

For #2211 an additional issue is that it seems to be based on a misunderstanding of the block. The block isn't "constant" in the Modelica sense, and the normal use cases don't rely on that.
We could just update its documentation to clarify that without any changes of the behavior.  Such issues are likely to occur because we use key-words such as "parameter", "inner", etc in Modelica that also have wider meanings.

--
To me it would make sense to just deprecate "constant" from the Modelica language (obviously allowing parameters in packages - or possibly just deprecate non-final constant), instead of trying to introduce "constant" and "parameter" as two kinds of parameters.

**Comment by henrikt-ma** [comment] 2019-09-20 09:03
> The underlying problem is that this is part of proposal to change the view of constant and parameter-evaluation in general, and to me that would create a large number of changes both in MSL and in user-libraries, and either create more confusion as some parameters would still be evaluated - or lock down current implementation limitations limiting re-use.

In order to get portability of simulation results, I believe that locking down structure-modifying behavior will be necessary at least to some degree.  If everything were just `parameter` and tools would need to decide for themselves what to evaluate, I don't think Modelica will ever become the tool-independent standard that it pretends to be.

By declaring what has structural impact as `constant` instead of relying on tool decisions, we should be able to get much better alignment of the equation systems being solved in different tools.  While some of the consequences of not solving the same equation systems in different tools is are just performance matters, we cannot ignore the fact that solving different equation systems means having different sets of variables for which to provide non-fixed start attributes.  This truly breaks portability of simulation results, as a model developed for one tool may not even initialize in the same way in a different tool.

**Comment by HansOlsson** [comment] 2019-09-20 09:34
> The underlying problem is that this is part of proposal to change the view of constant and parameter-evaluation in general, and to me that would create a large number of changes both in MSL and in user-libraries, and either create more confusion as some parameters would still be evaluated - or lock down current implementation limitations limiting re-use.
> 
> In order to get portability of simulation results, I believe that locking down structure-modifying behavior will be necessary at least to some degree.  If everything were just parameter and tools would need to decide for themselves what to evaluate, I don't think Modelica will ever become the tool-independent standard that it pretends to be.

I don't see that point at all.

When comparing models between tools we normally just compare their results without changing parameters. If we want to compare the model for two different sets of parameters we create two different models extending that base-model (or two different components within the same model). 

We haven't yet standardized simulating the same model for different parameter-sets and if/when we do we might as well standardize in a way that also handles evaluated parameters (by re-translating the model when needed). 

In Dymola and 3D Experience Platform we also have options to evaluate more parameters (regardless of model settings).

If that produces different results we view that as an issue that we need to solve. (Except the issue that there is a hidden singularity generating diagnostics for in-evaluated parameters, which either gives better diagnostics when evaluated - or in some cases is in fact automatically handled. Note that those parameters are normally unproblematic; further blurring the line between evaluated and non-evaluated parameters.)

> While some of the consequences of not solving the same equation systems in different tools is are just performance matters, we cannot ignore the fact that solving different equation systems means having different sets of variables for which to provide non-fixed start attributes. 

I agree that this could generate problems. But having the same set of equations don't imply the same set of iteration variables; so it is not a solution for that problem.

If we view non-fixed start-values as that important we instead should be stricter regarding them in other ways - similarly as we ensured that models in MSL have proper fixed start attributes instead of attempting to lock down the state-selection in MSL-models.

**Comment by henrikt-ma** [comment] 2019-09-20 09:41
> When comparing models between tools we normally just compare their results without changing parameters. If we want to compare the model for two different sets of parameters we create two different models extending that base-model (or two different components within the same model).

This doesn't have anything to do with changing the values of parameters.  This has to do with the unpredictable structural impacts of unpredictable evaluation of parameters during translation.  When something is declared `constant` it should be safe to assume that all tools use the value as much as they can to simplify equations.

**Comment by HansOlsson** [comment] 2019-09-20 11:34
> This has to do with the unpredictable structural impacts of unpredictable evaluation of parameters during translation.  

We need to see the actual examples of the possible problems caused by the (non-)evaluation of parameters to be able to understand this.

Currently I neither see evidence that it is an actual problem in practice (there are problems with the evaluation of parameters - but not this specific issue, except as specific bugs), nor that this change would solve those problems. And even if those problems exist and this change solves them it is not clear that this would be the best solution for the problem, especially as the proposed change causes a number of other issues.

**Comment by HansOlsson** [comment] 2020-12-11 18:23
More than a year without discussion. Closing, but it can be re-opened if new information appears.

**Closed by HansOlsson** 2020-12-11 18:23 UTC

**Comment by henrikt-ma** [comment] 2020-12-11 21:04
Yes, the stuck state probably means one will have to wait for the `Dialog` annotation.
