### ISSUE TITLE
stream connector spec causes singularity at constant zero flow

### ISSUE THREAD

**Issue by Mathadon** [modelica/ModelicaSpecification#3322] opened 2022-12-18 10:13 UTC
Section 15.2 of the Modelica specification contains:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/5970879/208292121-2acf5098-aa56-4003-8e81-452507f10cc2.png">

Suppose now that you have a water circulation pump component with two ports `port_a` and `port_b`. Where the pump is configured to have _constant_ flow rate `constant Modelica.Units.SI.MassFlowRate m_flow=0`.

The above quoted part of the spec then results in:
```modelica
inStream(port_a.h_outflow) = port_a.h_outflow
inStream(port_b.h_outflow) = port_b.h_outflow
```

furthermore, the pump equations typically contain:

```modelica
port_a.h_outflow = inStream(port_b.h_outflow)
port_b.h_outflow = inStream(port_a.h_outflow)
```
since a (simplified) pump does not modify the flow enthalpy.

These two sets of equations result in 4 variables and 4 equations that are all pointing to each other, which causes a singular system with infinitely many solutions. This (presumed) bug has caused about a year of delay on the development of https://github.com/open-ideas/IDEAS/pull/1296 . I propose to modify the Modelica specification to avoid this in the future.

Note that this problem does not appear when the mass flow rate is zero _or positive_ (or zero or negative) as a function of time since then different equations are generated for either `port_a` or `port_b`.

A good fix may not be easy to find. Possible lines of thought are:
1. `inStream(port_a.h_outflow) = <some default value, e.g. 0> ` in the `then` branch
The numerical value should not matter since it is multiplied by a mass flow rate of 0 for reasonable physics-based models. It however has a limitation: it does not allow to e.g. measure the temperature (which depends on enthalpy) through a pipe of zero flow.
2. Use the other part of the if/else branch:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/5970879/208292425-a8ead501-2a5b-4da1-94f2-a35497719310.png">
This however would introduce dependencies on variable values that are never used in cases where the flow in a pipe never reverses. This generates larger algebraic loops and is certainly not a good option.

3. Keep the current implementation but replace the `<=` by `<` and `>=` by `>` in the if branch. This results in the same problem as above for cases where the flow rate can only become positive, or exactly zero.
4. Implement a different equation depending on the mass flow rate variability: If the flow rate is always exactly zero, use option 1 or 2.

It could be interesting to organise a discussion about this with some people who are familiar with the stream equation implementation?

@mwetter @casella this may be relevant for your work on IBPSA project 1 and the Buildings library. @jelgerjansen @kldjonge fyi

**Comment by HansOlsson** [comment] 2022-12-19 08:08
> Section 15.2 of the Modelica specification contains:
> 
> <img alt="image" width="972" src="https://user-images.githubusercontent.com/5970879/208292121-2acf5098-aa56-4003-8e81-452507f10cc2.png">
> 
> Suppose now that you have a water circulation pump component with two ports `port_a` and `port_b`. Where the pump is configured to have _constant_ flow rate `constant Modelica.Units.SI.MassFlowRate m_flow=0`.
> 
> The above quoted part of the spec then results in:

However, you would not always end up in the "All other cases:" branch - and I would also expect that the other connections would often also cause the else-branch to be selected.

I believe we need to see the entire system to understand this better.

**Comment by mestinso** [comment] 2022-12-20 00:47
I'm curious about this one. Can you provide a MWE (minimum working example) that demonstrates the issue?

Also, to clarify: is it only an issue when using the constant prefix, or would it be the same for the parameter prefix?

**Comment by Mathadon** [comment] 2022-12-20 15:58
See MWE:

```modelica
model test
  package Medium = IDEAS.Media.Air;
  IDEAS.Fluid.Sources.Boundary_pT bou(redeclare package Medium = Medium, nPorts = 1) annotation(
    Placement(visible = true, transformation(origin = {-62, -10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  IDEAS.Fluid.Sources.MassFlowSource_h boundary_pT(redeclare package Medium = Medium, final m_flow = 0, nPorts = 1)  annotation(
    Placement(visible = true, transformation(origin = {90, -10}, extent = {{10, -10}, {-10, 10}}, rotation = 0)));
  IDEAS.Fluid.Movers.BaseClasses.IdealSource idealSource(dp=0,redeclare package Medium = Medium, control_m_flow = false, m_flow_small = 1)  annotation(
    Placement(visible = true, transformation(origin = {-12, -10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Fluid.Interfaces.FluidPort_a port_a(redeclare package Medium = Medium) annotation(
    Placement(visible = true, transformation(origin = {40, -10}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {-36, 36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(bou.ports[1], idealSource.port_a) annotation(
    Line(points = {{-52, -10}, {-22, -10}}, color = {0, 127, 255}));
  connect(idealSource.port_b, port_a) annotation(
    Line(points = {{-2, -10}, {40, -10}}, color = {0, 127, 255}));
  connect(boundary_pT.ports[1], port_a) annotation(
    Line(points = {{80, -10}, {40, -10}}, color = {0, 127, 255}));

annotation(
    uses(IDEAS(version = "3.0.0"), Modelica(version = "4.0.0")));
end test;
```

Without the fluid port (which is not connected on the exterior) the model does not fail:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/5970879/208709906-6358492f-8cbb-4e05-b97d-f9cf28089270.png">

Furthermore, without `final` (in `final m_flow=0` the model does not fail either. So parameter prefix would indeed work. This was tested with OMEdit.

**Comment by mestinso** [comment] 2022-12-20 17:45
@Mathadon I did a quick test here and I can at least report the following: I replicated the issue in OpenModelica. The code as is fails with the 0/0 error and the two changes you mentioned resolve it. Additionally, I also tested in Dymola and the 0/0 error does not occur for any of the cases.

Initial thoughts here:
1) Is it potentially a tool issue with OpenModelica's implementation for this scenario? My overall understanding based on the stream specification and intent is that the equations are supposed to be implemented in such a way that 0/0 type errors shouldn't be happening when zero flows occur. I don't see any reason this situation should be dependent on variability (at least based on the spec). Maybe there is an optimization/simplification that is happening in OpenModelica, but it wasn't implemented in a robust manner: maybe it should have been 0/eps instead of 0/0?
2) Or is Dymola not failing, but it should be (if it followed the spec more rigourously)? I'm not seeing the smoking gun that would point to this.

**Comment by HansOlsson** [comment] 2022-12-21 09:55
The only minor issues I have seen so far in the model are:

- Modifying dp for idealSource (that shouldn't be legal - but it isn't important).
- Dymola may generate a minor warning for port_a (since it is unusual to have a dangling public stream-connector).

**Comment by Mathadon** [comment] 2022-12-22 17:13
@mestinso , regarding your thoughts:

1. Dymola also fails for a more complex example. But for this MWE Dymola apparently works. Also, the four equations that I listed above clearly lead to a singular system, or am I misinterpreting them? The situation depends on variability since the tools can simplify the equation when they know that the mass flow rate is always zero. So it's not directly linked to the variability of the variable but rather the fact that the variable is always zero or just sometimes zero.
2. I'm not sure how dymola treats the equations in this case but it would indeed be interesting to have a look. If someone could post the dsmodel.mof file I'd be happy to check! (I don't have a license)

**Comment by Mathadon** [comment] 2022-12-22 17:17
> 

The issue is in the Modelica spec, not in the model :) 
There exist infinitely many solutions to this set of equations:

```modelica
inStream(port_a.h_outflow) = port_a.h_outflow
inStream(port_b.h_outflow) = port_b.h_outflow
port_a.h_outflow = inStream(port_b.h_outflow)
port_b.h_outflow = inStream(port_a.h_outflow)
```

and it would be nice if the Modelica spec would generate equations that have a (unique) solution.

**Comment by mestinso** [comment] 2022-12-22 19:18
> 1. Dymola also fails for a more complex example that I used to work on in the linked issue. But for this MWE Dymola apparently works. Also, the four equations that I listed above clearly lead to a singular system so I think this is a problem regardless of which tool is having problems with it. The situation depends on variability since the tools can simplify the equations when they know that the mass flow rate is always zero. So it's not directly linked to the variability of the variable but rather the fact that the variable is always zero or just sometimes zero, which coincides with the variability.

Sure, but the key question to me is whether the issue is with the spec or the tool implementation (which might have various corner cases and branches depending on variability). At least for the MWE posted, I'm inclined to think we are looking at a tool issue, not a spec issue. If there is a more sophisticated MWE, maybe that one should be posted.

**Comment by HansOlsson** [comment] 2023-01-02 07:47
> @HansOlsson
> 
> Don't you agree there exist infinitely many solutions to this set of equations:

Yes, but I don't see that the model imply those equations - as there are a number of cases when generating stream-equations intended to avoid such situations.

**Comment by Mathadon** [comment] 2023-01-02 07:56
okay thanks for clarifying! I'm working on a second MWE and will get back to you! Happy new year!

**Comment by HansOlsson** [comment] 2023-02-08 13:03
Closing until we get second MWE

**Closed by HansOlsson** 2023-02-08 13:03 UTC
Labels: worksforme, discussion
