### ISSUE TITLE
Mirror only connectors on graphical layer

### ISSUE THREAD

**Issue by paultjevdh** [modelica/ModelicaSpecification#3405] opened 2023-08-16 10:51 UTC
The way in which the 'extent' command in the Placement annotation is currently defined is that when a component is mirrored, its complete graphical layer is mirrored, including all connections as well as the graphical symbol indicating the function of the block. As an example I present two low-pass filter, one of which is mirrored.
![image](https://github.com/modelica/ModelicaSpecification/assets/59084059/4a54029b-8f4f-430f-88cd-fdd2abeed323)
As you can see, for the lower block it is now difficult to see that it is in fact a low pass filter, it looks like a high-pass filter.
The intention of mirroring is typically to align the inputs and outputs of a block in a convenient way with respect to the rest of the diagram, while the function remains the same. Many times, mirroring the graphical layer together with the connections will cause similar issues as above because mirroring the graphical layer was never anticipated. 

Is it possible to (introduce a boolean to) partly exclude the graphical layer from mirroring, and apply mirror only to the connectors? This request includes both horizontal and vertical mirroring.
I understand this interferes with the current 'extent' definition since scaling and aspect ratio of the graphics must be preserved.

**Comment by HansOlsson** [comment] 2023-08-16 11:16
Seems like a duplicate of #2248

**Comment by paultjevdh** [comment] 2023-08-16 12:21
Yeah, you're right, thanks for pointing that out. I searched for 'mirror', not 'flipped'.

**Closed** 2023-08-25 08:22 UTC
Labels: duplicate
