### ISSUE TITLE
Clarification of GraphicItem origin value

### ISSUE THREAD

**Issue by adeas31** [modelica/ModelicaSpecification#2495] opened 2020-02-17 08:58 UTC
The specification specifies,

`Point origin = {0 , 0};`

So I interpret this as origin always having a default value of `{0, 0}`. However, I tested this using a very small example,

```
model X
  annotation (Icon(coordinateSystem(preserveAspectRatio=false), graphics={
          Rectangle(extent={{-80,80},{-40,40}})}), Diagram(coordinateSystem(
          preserveAspectRatio=false)));
end X;
```

If we open the above model in Dymola 2020 and OpenModelica 1.14 we get the same result i.e., a small rectangle on the icon layer.

![before-rotation](https://user-images.githubusercontent.com/4007231/74637972-581f0580-516b-11ea-90d9-5f4726e5052f.png)

Now rotate the rectangle clockwise in Dymola and OM. Dymola calculates the origin using the extents of the rectangle. On the other hand OM uses the default origin `{0, 0}` and rotates around it.

![after-rotation](https://user-images.githubusercontent.com/4007231/74638000-679e4e80-516b-11ea-902c-834661763670.png)

Wolfram SystemModeler shows the same behavior as of OpenModelica.

So the question is if we don't have origin defined in the actual Modelica code then should we use `{0, 0}` or calculate it using the extents?

**Comment by sjoelund** [comment] 2020-02-17 09:37
I guess you want to add the code for the rotated rectangles as well to make it easier to reproduce

**Comment by HansOlsson** [comment] 2020-02-17 11:03
> 
> So the question is if we don't have origin defined in the actual Modelica code then should we use `{0, 0}` or calculate it using the extents?

As I understand it this is related to the graphical _operations_ in different tools.

The Modelica specification is primarily about standarizing the interpretation of the Modelica code (including graphical annotations); but not details of the GUI - as it isn't even specified that tools shall have a "Rotate" operation.

In this case one could even imagine that tools had a setting for this, and I would thus propose to close it as "worksforme".

**Comment by adeas31** [comment] 2020-02-17 12:43
> As I understand it, this is related to the graphical operations in different tools.

> The Modelica specification is primarily about standarizing the interpretation of the Modelica code (including graphical annotations); but not details of the GUI - as it isn't even specified that tools shall have a "Rotate" operation.

This is also about interoperability among Modelica tools. Consider you build some library in Dymola and later want to modify this in OpenModelica or SystemModeler. By default Dymola doesn't set origin attribute for shapes and components. When OM or SM reads such a library it assumes origin to be zero and applies all later operations based on that.

As I understand both behaviors are correct but which one is more accurate with regard to the specification? Assuming origin to be `{0, 0}` OR calculating it from the extents of the shape provided when origin is not present in the actual Modelica code?

**Comment by svorkoetter** [comment] 2020-02-17 13:29
I don't see how it affects interoperability. The annotations that the tool writes back to the Modelica file will be correct to reproduce what you see in the original tool when that Modelica code is read into another tool. OM and SM don't _assume_ the origin is `{0,0}`; the origin _is_ `{0,0}` according to the specification if it's not explicitly written otherwise. Likewise, I'm sure Dymola also knows that the origin is `{0,0}`; it just chooses not to do interactive rotations around the origin. I would guess that even if you explicitly set the origin to be elsewhere, Dymola will still rotate around the object's centre when you rotate using the mouse. That's just a UI design choice (and arguably more intuitive since you can't see where the origin is anyway).

**Comment by casella** [comment] 2020-02-17 15:58
@adeas31, we would have a critical issue if some code with the same graphical annotation is rendered differently in different tools, regardless how it has been built. Do you have any example of that?

**Comment by adeas31** [comment] 2020-02-17 19:13
The problem is not that some tool is rendering differently (in that case I would have opened a ticket on tool's site). I am just trying to understand what does the specification says when there is no origin defined in the code. I mean if I open this model,
```
model X
  annotation (Icon(coordinateSystem(preserveAspectRatio=false), graphics={
          Rectangle(extent={{-80,80},{-40,40}})}), Diagram(coordinateSystem(
          preserveAspectRatio=false)));
end X;
```

Should I use origin `{0, 0}` or the centre of rectangle for operations like flipping or rotation? What does the standard says about it? @HansOlsson and @svorkoetter thinks that its up to tool but as I interpret the specification the standard enforce `{0, 0}` as origin. If that is the case we can this issue right now. But if we think that in absence of origin it makes more sense to use the centre of graphic item as origin then this needs to be clarified in the specification and then perhaps origin shouldn't have a default value.

**Comment by svorkoetter** [comment] 2020-02-17 20:25
No, @svorkoetter does not think it is up to the tool. I clearly stated in my previous reply that the spec says it's `{0,0}`. However, the spec _only_ talks about the semantics of annotations for rendering. It does not talk at all about how interactive graphical manipulations are to work. The latter is under no obligation to respect the former. All that matters is that a given combination of annotations, whether hand-written, or generated by a tool as a result of interactive manipulations, renders in the same way in all tools. That is currently the case, and the default origin is `{0,0}`, which is, to the best of my knowledge, respected by all Modelica tools.

**Comment by adeas31** [comment] 2020-02-17 20:56
OK excuse me for the misunderstanding so you do believe that the value of the origin in that case is `{0, 0}`, right?

> That is currently the case, and the default origin is {0,0}, which is, to the best of my knowledge, respected by all Modelica tools.

I don't agree as it is clearly not the case in Dymola unless there is some hidden Dymola flag to switch between two behaviors.

**Comment by svorkoetter** [comment] 2020-02-17 22:29
@adeas31, Dymola's (or any tool's) _interactive_ behaviour has _nothing_ to do with the annotations. The origin that it (or any other tool) uses for interactive rotation need not be the same as the origin used for describing what is to be drawn and where. All that matters is that

1. If a tool reads Modelica graphical annotations, that it renders them correctly (i.e. all tools will render them the same way).
2. If a tool takes the end result of your interactive manipulations and produces Modelica annotations, these annotations will be correct such that any other tool will render what you produced in the originating tool.

What happens within the tool (such as rotating things with the mouse) between items 1 and 2 is not relevant, and is not covered by the specification.

Try the following experiment. Start with your example, loaded into Open Modelica. Rotate the rectangle, and save the resulting model. Now open this model in Dymola. You should see the rectangle in the same location that the rotation in OM moved it to. (If you don't, then either OM wrote out incorrect annotations, or Dymola misinterpreted them.)

**Comment by HansOlsson** [comment] 2020-02-18 17:14
Agreement in design group that a tool-issue and no need to change specification.

**Closed by HansOlsson** 2020-02-18 17:14 UTC
Labels: question
