### ISSUE TITLE
interpretation of fontSize attribute in Text objects

### ISSUE THREAD

**Issue by max-privato** [modelica/ModelicaSpecification#2303] opened 2018-12-29 14:30 UTC
In sect. 18.6.5.5 I read:
"If the fontSize attribute is 0 the text is scaled to fit its extent. Otherwise, the size specifies the absolute size."
It is not clear to me what "absolute size" means. I suppose it is not clear to tools developers as well, since they interpret this information differently from each other.
Consider the following snippet:

```mo
model m
equation
annotation(
    Diagram(graphics = {Text(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, textString = "text", fontSize = 12)}));
end m;
```

Dymola interprets this so that the text size remains the same when you enlarge or shrink the model page size; on the opposite side, OpenModelica changes Text size proportionally to the page size.

I have not a precise idea of what behaviour is the intended one. For me both (Dymola's and OM's) are acceptable. What for me is not acceptable is that the specification is not clear enough and its consequence, i.e. that different tools interpret this part of the Modelica specification  in different ways.

So, either fontSize=12 means 12 points, or it means a well-specified part of the page size (page width?, height?).
Or maybe some flag can be added so that users can choose between the two behaviours?

**Comment by DagBruck** [comment] 2019-01-07 09:33
The specification also documents the unit as "points", the declaration of the attribute is

> Real fontSize = 0 "unit pt";

However, in Dymola you can zoom the graphical representation of the model, which will change the size of the text on the screen. In Dymola zooming is not coupled to window size, but it is quite possible that OpenModelica has chosen differently.

**Comment by DagBruck** [comment] 2019-01-07 09:43
> In Dymola zooming is not coupled to window size, 

I should add "any more". Years ago Dymola would zoom as window size changed.

**Comment by sjoelund** [comment] 2019-01-07 10:16
@adeas31 what's the size of a point in OMEdit? From what I can tell, you calculate the size relative to the bounding box of the font which makes it an absolute value relative to the diagram (perhaps scaled wrongly on 4K screens).

**Comment by max-privato** [comment] 2019-01-07 18:40
> @adeas31 what's the size of a point in OMEdit? From what I can tell, you calculate the size relative to the bounding box of the font which makes it an absolute value relative to the diagram (perhaps scaled wrongly on 4K screens).

On a Windows system the standard DPI value used to be (and still it is on most systems) 96 DPI. This means that on these systems a 12 point font has 12*96/72=16 pixels height. 
On hi-RES monitors (such as 4k screens) if the font size in Qt software is specified in points, the font height is automatically scaled proportional to actual virtual DPIs.  It it is specified in pixels the programmer should take care of actual DPI value.
The situation on Mac systems is slightly different, but can be easily managed as well.
So, font size is easily managed in Qt, _once one knows what to do._

The real issue, for me, is that specification is not clear on what it requests. This implies difference in behaviour between tools, and, for me, this is not good and should be corrected (at the specification level).

**Comment by adeas31** [comment] 2019-01-14 14:56
> @adeas31 what's the size of a point in OMEdit? From what I can tell, you calculate the size relative to the bounding box of the font which makes it an absolute value relative to the diagram (perhaps scaled wrongly on 4K screens).

Yes I calculate the size relative to bounding box of the font unless it exceeds the actual bounding box of the component. Perhaps the issue is the 4k screen DPI. The standard is 96. We had the similar issue with `QWebView` which uses a fixed 96 dpi and doesn't scale well for 4k screens.

**Comment by DagBruck** [comment] 2019-01-15 13:59
> The real issue, for me, is that specification is not clear on what it requests. This implies difference in behaviour between tools, and, for me, this is not good and should be corrected (at the specification level).

What do you think is unclear?

1. Do you agree that the specification says font size is specified in points (pt) and 1 pt = 1/72 inch?
2. Do you agree that a tool may allow zooming in or out, or do you want to make it illegal to zoom?

**Comment by sjoelund** [comment] 2019-01-15 14:24
Of course a tool may zoom in/out. The normal for applications is that you can zoom in on text to make it more readable though (like OMEdit does); not to keep the font-size constantly unreadable. It's a slightly different design you make in your models depending on if the fonts should zoom in or not.

**Comment by HansOlsson** [comment] 2020-02-12 13:44
The status does not seem clear for this after a year. 
@DagBruck @sjoelund  can you clarify what is the actual issue, and propose to improve it?

**Comment by HansOlsson** [comment] 2020-12-11 17:41
Duplicate of #2707 (or the opposite).

**Closed by HansOlsson** 2020-12-11 17:41 UTC
Labels: duplicate
