### ISSUE TITLE
Standardize platform names for non-x86 platforms

### ISSUE THREAD

**Issue by t-sommer** [modelica/ModelicaSpecification#3484] opened 2024-02-22 12:52 UTC
Currently the MLS defines platform names only for Windows and Linux on 32-bit and 64-bit x86 in [12.9.4 Annotations for External Functions](https://specification.modelica.org/master/functions.html#external-function-interface):

>  The following platform names are standardized:
> – "win32" (Microsoft Windows 32 bit)
> – "win64" (Microsoft Windows 64 bit)
> – "linux32" (Linux Intel 32 bit)
> – "linux64" (Linux Intel 64 bit)

I propose to adopt the [platform tuple of FMI 3.0](https://fmi-standard.org/docs/3.0.1/#platform-tupe-definition) to support other operating systems and architectures.

**Comment by HansOlsson** [comment] 2024-02-22 12:54
Duplicate of #3453

**Closed by HansOlsson** 2024-02-22 12:54 UTC
Labels: duplicate
